### PR TITLE
Fixed apt cleanup (Issue #78)

### PR DESCRIPTION
**Pull request by JKJameson**

### CODE REVIEW

**Comment by JKJameson** [comment]
Please don't merge my commit 57681a5 - it is a draft I just finished. Not sure how it's getting pulled into this PR.

**Comment by colinmollenhour** [comment]
Oops, yeah I thought I was just merging the one commit..

**Comment by JKJameson** [comment]
I still see the commit merged with master. If you would like to undo the merge I will create a new branch and resubmit a new PR.

**Comment by colinmollenhour** [comment]
I reverted 57681a5fc040c7bdef93607278a3ce6bea7339aa in master.

**Pull request merged**
