### PR TITLE
use ip's of container instead of vip or dnsrr

### PR DESCRIPTION
**Pull request by olafbuitelaar**
I realize this an old commit, thus will probably not be compatible. When i came across your repo i thought it looked really neat, only for the swarm setup i wanted to address the nodes (and build the --wsrep_cluster_address= argument) via it's container ip instead of using it's VIP/LoadBalancer address, or using DNSRR.
The container ip's could be resolved using the special swarm dns lookup; getent hosts <tasks.SERVICE-NAME>, e.g;
```
root@27e6ccaf1f70:/# getent hosts tasks.seed
10.0.22.8       tasks.seed
root@27e6ccaf1f70:/# getent hosts tasks.node
10.0.22.95      tasks.node
10.0.22.6       tasks.node
```
see line 298 in start.sh, where this is implemented. the rest of start.sh is just to deal with this change.

I think the following changes needs to be at least done before you should consider the pull request;
* needs to brought up to date
* you probably want a some settings to choose the resolve method, either, dnsrr, vip or container-ip.
* proper logging

### CODE REVIEW

**Comment by colinmollenhour** [comment]
Why not just pass "tasks.X" as the command argument?

**Comment by olafbuitelaar** [comment]
I've actually not tried that. But when i just changed https://github.com/colinmollenhour/mariadb-galera-swarm/blob/master/start.sh#L326 which achieves the same goal, i ended up with several issues (if memory serves me well).

- timing issues, since the tasks.X might not be filled yet with the container ip's; hence the introduction of $GCOMMTMP and $EMPTYFLAG for allowing a longer wait
- off by 1 error with $GCOMM_MINIMUM, since it was set to 2, but with seed + 2 normal nodes, this should be 3. also when later migrating away from the seed node, to 3 regular nodes. due to the [ $COUNT -lt $(($GCOMM_MINIMUM - 1))
- the server references itself in the --wsrep_cluster_address, hence the latest replace; GCOMM=${GCOMM//$NODE_ADDRESS/}. I believe the documentation seemed to suggest it prefers to specify all other nodes excluding the same node.

Did you had success with just changing to tasks.X in the command line?

**Comment by colinmollenhour** [comment]
I haven't tried it with swarm in a long time.. I couldn't really tell what your PR was changing since it looks like it reverts a bunch of other changes so it needs to be cleaned up. Also, this needs to remain compatible with other systems besides swarm so hardcoding `tasks.` anywhere is not ok unless there is a special environment variable or build arg to enable it.

**Comment by olafbuitelaar** [comment]
It's only regarding the changes in start.sh. If you're open for such an approach, i can make a cleaner PR

**Comment by colinmollenhour** [comment]
Yes, I'm always open to improvements, just needs to consider the generalized environments and not just swarm. Thanks!

**Comment by luisfavila** [comment]
@colinmollenhour sorry to barge in, but is it now possible to not use dnsrr? I'd like to be able to expose ports as `ingress`

**Comment by colinmollenhour** [comment]
Yes, please see the Docker Swarm example, the command is "node tasks.seed,tasks.node" and all IPs that resolve are used as node addresses.

**Comment by luisfavila** [comment]
@colinmollenhour was just checking since the example has `endpoint_mode: dnsrr`

**Comment by colinmollenhour** [comment]
Yes I think that has not been necessary since https://github.com/colinmollenhour/mariadb-galera-swarm/commit/3723c2a784d105d9ea84e5118d13414174a0f26b.

**Pull request closed without merging**
